# Generated by Django 3.0.3 on 2020-04-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200418_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.TextField(default='backfill'),
            preserve_default=False,
        ),
    ]
