# Generated by Django 3.0.3 on 2020-05-04 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_tictactoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='cell1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell7', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell8', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='cell9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell9', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
